In [1]:
import pandas as pd

In [5]:
print(pd.__version__)  #checking pandas version

2.2.2


In [6]:
#creating a series in pandas , basically pandas stand on the top of numpy 

Initailizing Values 

In [8]:
A= pd.Series([2,3,4,5],index=['a','2','c','d']) # you can set  your keys index to the values otherwise default is 0,1,2...

In [10]:
A['a']

2

In [12]:
A['2']

3

Accessing Values 

In [13]:
B=pd.Series([1,2,3,4,5,6])

In [14]:
#now by default accessing 

B[2]

3

Accessing values of the list and the indexs list 

In [16]:
type(A)

pandas.core.series.Series

In [18]:
type(A.values)

numpy.ndarray

In [19]:
A.values

array([2, 3, 4, 5], dtype=int64)

In [20]:
B.values

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [21]:
B.index 

RangeIndex(start=0, stop=6, step=1)

In [22]:
A.index

Index(['a', '2', 'c', 'd'], dtype='object')

Slicing 

In [32]:
A['a':'c']

a    2
2    3
c    4
dtype: int64

In [2]:
"""one thing to notice here  if you do slicing with your own keys then in the slicing the end term will be included in slicing 
  other wise in default slicing with indexes 0,1,2,... ,end is not included""" 

'one thing to notice here  if you do slicing with your own keys then in the slicing the end term will be included in slicing \n  other wise in default slicing with indexes 0,1,2,... ,end is not included'

In [37]:
B[0:4] 

0    1
1    2
2    3
3    4
dtype: int64

In [39]:
C=pd.Series([1,2,3,4,5],index=['a','b',0,1,2])

In [42]:
print(C[0:3])#ordinary slicing 

a    1
b    2
0    3
dtype: int64


In [43]:
print(C['a':1])#key slicing 

a    1
b    2
0    3
1    4
dtype: int64


In [44]:
D=pd.Series([1,2,3,4,5,6,7],index=[0,1,2,3,4,5,6])


In [46]:
D[0:2] # here you define the keys as default indexes , notebook confuses and choses the default key

0    1
1    2
dtype: int64

Make a Dictionary and pass it to the series it will make a list of values and indexes 

In [47]:
D_Grades={1:2,2:3,4:5,6:7}

In [48]:
D=pd.Series(D_Grades)

In [52]:
D.values

array([2, 3, 5, 7], dtype=int64)

In [53]:
D.index

Index([1, 2, 4, 6], dtype='int64')

In [56]:
#Data Frames 

In [3]:
grades={'A':85,'B':80,'C':75,'C+':70,'D':65,'D+':60,'E':55,'E+':50}

marks={'A':4,'B':3.7,'C':3.3,'C+':3,'D':2.7,'D+':2,'E':1.5,'E+':1}

In [4]:
d=pd.DataFrame({'gradi':marks,'marki':grades})

In [5]:
d

gradi  marki
A     4.0     85
B     3.7     80
C     3.3     75
C+    3.0     70
D     2.7     65
D+    2.0     60
E     1.5     55
E+    1.0     50

In [15]:
 d.values


array([[ 4. , 85. ],
       [ 3.7, 80. ],
       [ 3.3, 75. ],
       [ 3. , 70. ],
       [ 2.7, 65. ],
       [ 2. , 60. ],
       [ 1.5, 55. ],
       [ 1. , 50. ]])

In [6]:
d.index


Index(['A', 'B', 'C', 'C+', 'D', 'D+', 'E', 'E+'], dtype='object')

In [16]:
d.T # transpose

A     B     C    C+     D    D+     E    E+
gradi   4.0   3.7   3.3   3.0   2.7   2.0   1.5   1.0
marki  85.0  80.0  75.0  70.0  65.0  60.0  55.0  50.0

In [17]:
d.columns

Index(['gradi', 'marki'], dtype='object')

In [23]:
#if you want scaled version of marks 
# if  you want to calculate out of 120
d['scaled version ']=d['marki']/100*120

In [22]:
d

gradi  marki  scaled version 
A     4.0     85            102.0
B     3.7     80             96.0
C     3.3     75             90.0
C+    3.0     70             84.0
D     2.7     65             78.0
D+    2.0     60             72.0
E     1.5     55             66.0
E+    1.0     50             60.0

In [9]:
G=d[d['marki']>70]   #masking 

In [8]:
G

gradi  marki
A    4.0     85
B    3.7     80
C    3.3     75

In [5]:
A=pd.DataFrame([{'a':'A','b':'B' },{'b':'B','c':'C','a':'a'}])

In [6]:
A

a  b    c
0  A  B  NaN
1  a  B    C

In [7]:
A.fillna(1)

a  b  c
0  A  B  1
1  a  B  C

In [2]:
A=pd.DataFrame([{'a':'A','b':'B' },{'b':'B','c':'C','a':'a'}])
print(A.isna()) # returns true where nan present 
print (A)

       a      b      c
0  False  False   True
1  False  False  False
   a  b    c
0  A  B  NaN
1  a  B    C


In [13]:
A.dropna() # drop the row where nan is present 

a  b  c
1  a  B  C

In [17]:
A=pd.DataFrame([{'a':'A','b':'B' },{'b':'B','c':'C','a':'a'}])
A['c'].fillna('yes') # fills the  value of key'c' with 'yes'

0    yes
1      C
Name: c, dtype: object

In [3]:
#while slicing you encounter a problem in which your defined index clashes with default 
A

a  b    c
0  A  B  NaN
1  a  B    C

In [20]:
#in this Case you have to force compiler what you want it to do

In [22]:
a=pd.Series(['a','b','c','d'],index=[1,3,5,7])
a[1:3] #here it follows default index

3    b
5    c
dtype: object

In [24]:
#to follow yours:

a.loc[1:3]

1    a
3    b
dtype: object

In [25]:
#to follow default:

a.iloc[1:3]

3    b
5    c
dtype: object

In [26]:
# from now we will able to read csv file we will do it in next file